config/routes.rb
Rails.application.routes.draw do
  
  root 'articles#index'
  
  resources :articles
  resources :categories, except: [:show]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    
    belongs_to :category 
    
    validates :title, presence: true, length: { minimum: 5 }
    validates :body, presence: true, length: { minimum: 10 }

    paginates_per 2

    scope :desc_order, -> { order(created_at: :desc) }
    scope :whithout_highlights, ->(ids) { where("id NOT IN(#{ids})")if ids.present?} 
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :articles, dependent: :restrict_with_error

    validates :name, presence: true, length: { minimum: 3 }

    scope :sorted, -> { order(:name) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: %i[show edit update destroy]


  def index
    @highlights = Article.desc_order.first(3)
    
    current_page = (params[:page] || 1).to_i
    highlight_ids = @highlights.pluck(:id).join(",")
    @articles = Article.whithout_highlights(highlight_ids)
                       .desc_order                        
                       .page(current_page)
  end

  def show;  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article, notice: "Article was successfully created."
    else
      render :new
    end
  end

  def edit;  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: "Article was successfully updated."
    else
      render :edit
    end
  end


  def destroy
  @article.destroy
  redirect_to root_path, notice: "Article was successfully destroyed."
end

  private

  def article_params
    params.require(:article).permit(:title, :body, :category_id)
  end

  def set_article
    @article = Article.find(params[:id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.sorted
  end

    # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
   if @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  else 
    redirect_to categories_url, alert: @category.errors.messages[:base][0]
  end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def render_if(condition, template, record)
     render template, record if condition    
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
        def format_date(date)
            date.strftime('%B %e, %Y')
        end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/_about.html.erb
<div class="p-4 mb-3 bg-light rounded">
          <h4 class="fst-italic">About</h4>
          <p class="mb-0">Hello, welcome to my blog, my name is <b>Vitor Arruda</b> and I enjoy studying Ruby on Rails programming.</p>
</div>

    

app/views/articles/_archives.html.erb
      <div class="p-4">
          <h4 class="fst-italic">Archives</h4>
          <ol class="list-unstyled mb-0">
            <li><a href="#">March 2021</a></li>
            <li><a href="#">February 2021</a></li>
            <li><a href="#">January 2021</a></li>
            <li><a href="#">December 2020</a></li>
            <li><a href="#">November 2020</a></li>
            <li><a href="#">October 2020</a></li>
            <li><a href="#">September 2020</a></li>
            <li><a href="#">August 2020</a></li>
            <li><a href="#">July 2020</a></li>
            <li><a href="#">June 2020</a></li>
            <li><a href="#">May 2020</a></li>
            <li><a href="#">April 2020</a></li>
          </ol>
        </div>

app/views/articles/_article.html.erb
<article class="blog-post">
        <h2 class="blog-post-title">New feature</h2>
        <p class="blog-post-meta"><%= format_date(article.created_at) %> by <a href="#">Chris</a></p>

        <p><%= truncate(article.body, length: 150) %></p>

          <p><%= link_to 'Continue reading ...', article_path(article), class: 'btn btn-link' %></p>

        <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-secondary' %> 
        <%= link_to 'Destroy', article_path(article),
        method: :delete,
        data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>

        </article>

app/views/articles/_elsewhere.html.erb
<div class="p-4">
          <h4 class="fst-italic">Elsewhere</h4>
          <ol class="list-unstyled">
            <li><a href="#">GitHub</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Facebook</a></li>
          </ol>
        </div>
      </div>

app/views/articles/_form.html.erb
<%= simple_form_for article do |f| %>
    <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body, input_html: { rows: 10 } %>
    <%= f.association :category, collection: Category.sorted, prompt: 'Select a category' %>
    </div>

    <div class="form-actions">    
      <%= f.button :submit, class: 'btn btn-primary' %>
      <%= link_to 'Back', root_path, class: 'btn btn-secondary' %>

    </div>

<% end %>

 

app/views/articles/_longer_featured.html.erb
<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 fst-italic"><%= article.title %></h1>
      <p class="lead my-3">
        <%= truncate(article.body, length: 100) %> </p>
      <p class="lead mb-0">
        <%= link_to 'Continue reading...', article, class: 'text-white fw-bold' %> </p>
    </div>
  </div>

app/views/articles/_medium_featured.html.erb
<div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">

          <strong class="d-inline-block mb-2 text-primary">
            <%= article.category.name %>
          </strong>

          <h3 class="mb-0"><%= article.title %></h3>

          <div class="mb-1 text-muted"><%= format_date(article.created_at) %></div>

          <p class="card-text mb-auto">
          <%= truncate(article.body, length: 150) %> </p>

          <%= link_to 'Continue reading...', article, class: 'stretched-link' %>

        </div>
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

        </div>
      </div>
    </div>
    

app/views/articles/_pagination.html.erb
<nav class="blog-pagination" aria-label="Pagination">
    <%= link_to_next_page @articles, 'Older', class: 'btn btn-outline-primary' %>
    <%= link_to_previous_page @articles, 'Newer', class: 'btn btn-outline-secondary' %>
</nav>

app/views/articles/_right_side.html.erb
<div class="col-md-4">
      <div class="position-sticky" style="top: 2rem;">
       
      <%= render 'about' %> 
      <%= render 'archives' %>
      <%= render 'elsewhere' %>  
      
      </div>
    </div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

     <%= render 'form', article: @article %>

app/views/articles/index.html.erb
<%= render_if @highlights[0].present?, 'longer_featured',  article: @highlights[0] %>

<div class="row mb-2">
  <%= render_if @highlights[1].present?, 'medium_featured', article: @highlights[1] %>
  <%= render_if @highlights[2].present?, 'medium_featured', article: @highlights[2] %>
</div>
      
    <div class="row g-5">
     <div class="col-md-8">
      <h3 class="pb-4 mb-4 fst-italic border-bottom">
        From my Experience
      </h3>
      
      
      <p>
      <%= link_to 'New Article', new_article_path, class: 'btn btn-primary' %>
      </p>
        
      <%= render @articles %>
      
      <%= render 'pagination' %>
     </div>

     <%= render 'right_side' %>
     </div>

app/views/articles/new.html.erb
<h1>New Article</h1>

  <%= render 'form', article: @article %> 

app/views/articles/show.html.erb
<article class="blog-post">
        <h2 class="blog-post-title">New feature</h2>
        <p class="blog-post-meta"><%= format_date(@article.created_at) %> by <a href="#">Chris</a></p>

        <p><%=@article.body %></p>


        <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-secondary' %> 
        <%= link_to 'Destroy', article_path(@article),
        method: :delete,
        data: { confirm: 'Are you sure?' },
        class: 'btn btn-danger' %>

        <%= link_to 'Back', root_path, class: 'btn btn-secondary' %>

        </article>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

      <p>  <%= link_to 'New Category', new_category_path, class: 'btn btn-primary' %>   </p>

<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
         <td>
         <%= link_to 'Show', category %>
         <%= link_to 'Edit', edit_category_path(category) %>
         <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_flash_messages.html.erb
<% if notice.present? %>
   <div class="alert alert-success" role="alert"> 
    <%= notice %>
   </div>
   
<% end %>

<% if alert.present? %>
   <div class="alert alert-danger" role="alert">
     <%= alert %>  
   </div>

<% end %>

app/views/layouts/_footer.html.erb
<footer class="blog-footer">
  <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/layouts/_topnavbar.html.erb
<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
         <%= link_to "Categories", categories_path, class: 'link-secondary' %>
      </div>
      <div class="col-4 text-center">
        <%= link_to "Vitor Arruda Blog", root_path, class: 'blog-header-logo text-dark' %>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="link-secondary" href="#" aria-label="Search">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
        </a>
        <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
      </div>
    </div>
  </header>

  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <a class="p-2 link-secondary" href="#">World</a>
      <a class="p-2 link-secondary" href="#">U.S.</a>
      <a class="p-2 link-secondary" href="#">Technology</a>
      <a class="p-2 link-secondary" href="#">Design</a>
      <a class="p-2 link-secondary" href="#">Culture</a>
      <a class="p-2 link-secondary" href="#">Business</a>
      <a class="p-2 link-secondary" href="#">Politics</a>
      <a class="p-2 link-secondary" href="#">Opinion</a>
      <a class="p-2 link-secondary" href="#">Science</a>
      <a class="p-2 link-secondary" href="#">Health</a>
      <a class="p-2 link-secondary" href="#">Style</a>
      <a class="p-2 link-secondary" href="#">Travel</a>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">



    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/topnavbar' %>

    <main class="container">
      <%= render 'layouts/flash_messages' %>
    <%= yield %>
    </main>

    <%= render 'layouts/footer' %>
  </body>
</html>